name: Make release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - run: go get .
      - run: GOOS=linux GOARCH=386 go build -a -o go-eink-linux-i386
      - run: GOOS=linux GOARCH=amd64 go build -a -o go-eink-linux-amd64
      - run: GOOS=linux GOARCH=arm64 go build -a -o go-eink-linux-arm64
      - run: GOOS=windows GOARCH=386 go build -a -o go-eink-windows-i386.exe
      - run: GOOS=windows GOARCH=amd64 go build -a -o go-eink-windows-amd64.exe
      - run: GOOS=windows GOARCH=arm64 go build -a -o go-eink-windows-arm64.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            go-eink-linux-i386
            go-eink-linux-amd64
            go-eink-linux-arm64
            go-eink-windows-i386.exe
            go-eink-windows-amd64.exe
            go-eink-windows-arm64.exe
